### ISSUE TITLE
uppercase versus lowercase x,y

### ISSUE THREAD

**Issue by jeromew** [junmer/clipper-lib#4]
I understand that this lib needs points to be represented as { X:, Y: }.
It seems to me that many npm modules rely on the fact that points are defined as {x:, y:} because of this specification https://github.com/colinmeinke/points.

would it make sense to change this library to use the lowercase version, or to accept both versions ?

it would avoid a systematic impedance transformation when integrating several libs.

**Comment by junmer** [comment]
hi @jeromew ,this repo is only fork from <https://sourceforge.net/projects/jsclipper/> . please open a issue at <https://sourceforge.net/p/jsclipper/tickets/>
thank you

**Comment by jeromew** [comment]
ok thanks. I'll close it here and look on jsclipper if it was already discussed.
